version: '2.1'
services:
    redis:
        image: redis:latest
        command: redis-server

    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
             - ../pgdata:/var/lib/postgresql/data/pgdata

    webserver:
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
#            - REDIS_PASSWORD=redispass
        volumes:
            - ../dags:/usr/local/airflow/dags
            - ../plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: always
        depends_on:
            - webserver
        volumes:
            - ../dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            - ../plugins:/usr/local/airflow/plugins
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        command: scheduler

    worker:
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ../dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            - ../plugins:/usr/local/airflow/plugins
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        command: worker
